require('dotenv').config();

const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const morgan = require('morgan');
const rateLimit = require('express-rate-limit');
const opportunitiesRouter = require('./routes/opportunities');
const scoringRouter = require('./routes/scoring');
const passportsRouter = require('./routes/passports');
const matchingRouter = require('./routes/matching');
const leadsRouter = require('./routes/leads');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(helmet());
app.use(cors({ origin: ['https://capitalos.co.za','https://www.capitalos.co.za','https://app.capitalos.co.za','https://capitalos-za.netlify.app',process.env.CAPITALOS_OPERATOR_URL/'http://localhost:3000','http://localhost:5173'].filter(Boolean), credentials: true }));
app.use(express.json({ limit: '5mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(morgan('combined'));
const apiLimiter = rateLimit({ windowMs: 15*60*1000, max: 500, message: { error: 'Too many requests' } });
const publicLimiter = rateLimit({ windowMs: 60*60*1000, max: 100, message: { error: 'Rate limit reached' } });
app.use('/api/', apiLimiter);
app.use('/api/v2/leads', publicLimiter);
app.use('/api/v2/opportunities', opportunitiesRouter);
app.use('/api/v2/scoring', scoringRouter);
app.use('/api/v2/passports', passportsRouter);
app.use('/api/v2/matching', matchingRouter);
app.use('/api/v2/leads', leadsRouter);
app.get('/health', (req,res) => res.json({ status:'healthy', service:'capitalos-api', version:'1.0.0', timestamp:new Date().toISOString(), environment:process.env.NODE_ENV||'production' }));
app.get('/', (req,res) => res.json({ name:'CapitalOS API', version:'v2' }));
app.use((req,res) => res.status(404).json({ error:`Endpoint ${req.method} ${req.path} not found` }));
app.use((err,req,res,next) => { console.error('Error:',err); res.status(500).json({ error: err.message }); });
app.listen(PORT, () => console.log(`CapitalOS API v2 running on port ${PORT}`));
module.exports = app;
